remote_theme: mmistakes/minimal-mistakes
title: ESG Insights Semanal
description: Portal independente de notícias sobre sustentabilidade e economia circular
url: "https://ambisocial.github.io"
baseurl: "/esg-insights-semanal"
author: Redação ESG Insights Semanal
email: contato@esg-insights-semanal.com
lang: pt-BR
timezone: America/Sao_Paulo
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache
markdown: kramdown
highlighter: rouge
paginate: 10
paginate_path: "/page:num/"
search: true
